version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  deploy-preview:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "hello world"

workflows:
  preview:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - deploy-preview
