version: 2.1

orbs:
    node: circleci/node@5.0.3

jobs:
    deploy-preview:
        docker:
            - image: cimg/node:18.10.0
        steps:
            - checkout
            - run: echo "hello world"
    build:
        docker:
            - image: node:18
        resource_class: large
        parallelism: 10

        steps:
            - checkout
            - restore_cache:
                  name: Restore pnpm and next build Package Cache
                  keys:
                      - dependency-cache-{{ checksum "pnpm-lock.yaml" }}
            - run:
                  name: Install pnpm package manager
                  command: |
                      curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7
            - run:
                  name: Install Dependencies
                  command: |
                      pnpm install
            - run:
                  name: Build project
                  command: |
                      pnpm build
            - save_cache:
                  name: Save pnpm and next build Package Cache
                  key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
                  paths:
                      - node_modules
                      - ./.next/cache

workflows:
    preview:
        triggers:
            - schedule:
                  cron: '0 0 * * *'
                  filters:
                      branches:
                          ignore:
                              - main
        jobs:
            - deploy-preview
    deploy:
        jobs:
            - build
